# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 222060c4c2870338a599bd3a26bef26a6b24758e28116d24ec03a3041ffedeb031ad8fe2f12430b353c5dc00d06526d66060a3331695e18961a39879e213dd4a

test:
  secret_key_base: f6e2c9979430cbcae39f439f38e9a80e235a05be69d92ead4277a48272e7edc9cd2a04ea117b6fa06e16de78082c1b5271114a9ded870adbc3c12176106cf7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
